# NOTE !! iam new to docker but i managed to search for how to build an image with mysql
# for unknown reason this script is getting error connecting to mysql 
# In my opinion the problem arises with the mysql connector that installed in the environment



version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: simpledb
      MYSQL_PASSWORD: msyql
      MYSQL_ROOT_PASSWORD: mysql
  web:
    build: .
    command: python bit/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db