version: '3.7'

services:
  db:
    image: mysql:8.0
    restart: always
    volumes:
      - ./mysql_data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: simpledb
      MYSQL_PASSWORD: msyql
      MYSQL_ROOT_PASSWORD: mysql
  web:
    build: .
    command: python bit/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db