version: '3.7'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'simpledb'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: '12345'
      MYSQL_ROOT_PASSWORD: '12345'
  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
      - .:/code
    env_file:
      - ./.json
    ports:
      - "8000:8000"
    depends_on:
      - db